version: '3'

services:
  flask_app:
    build:
      context: .
      dockerfile: docker_files/FlaskDockerfile
    image: ziyadabd/intelli-season-flask-app:1.0.0
    container_name: flask-app-cont
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - streamlit_app

  streamlit_app:
    build:
      context: .
      dockerfile: docker_files/StreamlitDockerfile
    image: ziyadabd/intelli-season-streamlit-app:1.0.0
    container_name: streamlit-app-cont
    ports:
      - "8501:8501"
    env_file:
      - .env
