"""
This is a shared dict that will keep the login sessions with streamlit
"""

# Stores the user's session information
state_store = dict()

# Stores the responses generated by different models
global_model_response = list()
